import { useEffect, useState } from "react"
import { Link } from "@tanstack/react-router"
import { Button } from "@renderer/components/ui/button"
import { Input } from "@renderer/components/ui/input"
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogAction, AlertDialogCancel } from "@renderer/components/ui/alert-dialog"
import type { DiagnosticFilter, DiagnosticReport } from "@shared/maintenance-settings-types"
import { maintenanceApi } from "./usage-settings"
import { errorMessage } from "./settings-error-message"

export function DiagnosticsSettings() {
  const [report, setReport] = useState<DiagnosticReport | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [feedback, setFeedback] = useState("")
  const [filter, setFilter] = useState<DiagnosticFilter>({}); const [restartOpen, setRestartOpen] = useState(false)
  const [detailsExpiry, setDetailsExpiry] = useState<number | null>(null)
  async function act(work: () => Promise<unknown>, message: string) { setBusy(true); try { const result = await work(); setFeedback(typeof result === "string" ? `已导出到 ${result}` : message); setError("") } catch (error) { setError(errorMessage(error)) } finally { setBusy(false) } }
  async function diagnose() { await act(async () => setReport(await maintenanceApi().diagnose()), "检查结束；各项状态如下") }
  useEffect(() => { void diagnose(); const readDetails = () => Promise.resolve().then(() => maintenanceApi().diagnosticDetails()).then(value => setDetailsExpiry(value.expiresAt)).catch(() => {}); void readDetails(); const timer = setInterval(() => { void readDetails() }, 15_000); return () => { clearInterval(timer); void Promise.resolve().then(() => maintenanceApi().cancelDiagnosis()).catch(() => {}) } }, [])
  const logs = (report?.logs ?? []).filter(row => (!filter.from || row.time >= filter.from) && (!filter.level || row.level === filter.level) && (!filter.module || row.module === filter.module) && (!filter.runId || row.runId === filter.runId)) .map(log => { if (detailsExpiry && detailsExpiry > Date.now()) return log; const { requestId: _request, toolName: _tool, method: _method, ...basic } = log; return basic })
  return <div className="flex flex-col gap-8"><section id="diagnostics-status" className="space-y-3"><h2 className="text-sm font-semibold">服务与只读检查</h2><p className="text-xs text-muted-foreground">检查不会调用模型、发送外部消息或安装软件。单项最长 15 秒，可取消。重新连接只刷新连接；重启会关闭当前后台服务。</p><div className="flex flex-wrap gap-2"><Button size="sm" disabled={busy} onClick={() => void diagnose()}>重新检查</Button>{busy ? <Button size="sm" variant="ghost" onClick={() => void maintenanceApi().cancelDiagnosis()}>取消检查</Button> : null}<Button size="sm" variant="outline" disabled={busy} onClick={() => void act(() => maintenanceApi().reconnect(), "已重新连接后台服务")}>重新连接</Button><Button size="sm" variant="outline" disabled={busy} onClick={() => void act(async () => { setReport(await maintenanceApi().diagnose()); setRestartOpen(true) }, "重启前清单已刷新")}>安全重启后台服务</Button></div>
  {error ? <p role="alert" className="text-sm text-destructive">{error}</p> : null}{feedback ? <p role="status" className="text-xs text-muted-foreground">{feedback}</p> : null}
  {!report ? <p role="status" className="text-sm">{busy ? "正在检查…" : "尚无检查结果"}</p> : <><p className="text-xs text-muted-foreground">桌面 {report.desktopVersion} · {report.platform} / {report.architecture} · 连接 {report.target ?? "未连接"} · {new Date(report.checkedAt).toLocaleString()}</p><div className="divide-y">{report.checks.map(check => <div key={check.id} className="py-3 text-sm"><div className="flex justify-between"><span>{check.name}</span><span className={check.status === "failed" ? "text-destructive" : "text-muted-foreground"}>{{ success: "成功", warning: "警告", failed: "失败", unsupported: "不支持", timeout: "超时", cancelled: "已取消" }[check.status]}</span></div><p className="text-xs text-muted-foreground">{check.detail}</p></div>)}</div>{report.missing.length ? <p className="text-xs text-muted-foreground">未取得：{report.missing.join("、")}</p> : null}</>}</section>
  <section id="diagnostics-logs" className="space-y-3"><h2 className="text-sm font-semibold">脱敏运行日志</h2><div className="flex flex-wrap items-end gap-3"><label className="text-xs">时间<select className="ml-2 rounded border bg-background p-2" onChange={event => setFilter(previous => ({ ...previous, from: event.target.value ? Date.now() - Number(event.target.value) * 86400000 : undefined }))}><option value="">全部已读取</option><option value="1">最近 24 小时</option><option value="7">最近 7 天</option></select></label><label className="text-xs">级别<select className="ml-2 rounded border bg-background p-2" value={filter.level ?? ""} onChange={event => setFilter(previous => ({ ...previous, level: event.target.value }))}><option value="">全部</option>{["debug", "info", "warn", "error"].map(level => <option key={level}>{level}</option>)}</select></label><label className="text-xs">模块<Input value={filter.module ?? ""} onChange={event => setFilter(previous => ({ ...previous, module: event.target.value }))} /></label><label className="text-xs">关联任务 ID<Input value={filter.runId ?? ""} onChange={event => setFilter(previous => ({ ...previous, runId: event.target.value }))} /></label></div>
  {!logs.length ? <p className="text-sm text-muted-foreground">当前筛选没有可读取的结构化日志。原始文本日志不会被直接显示或导出。</p> : <div className="max-h-96 overflow-auto divide-y">{logs.map((log, index) => <div key={`${log.time}:${index}`} className="flex items-start justify-between gap-3 py-2 text-xs"><div>{log.time ? new Date(log.time).toLocaleString() : "未记录时间"} · {log.level} · {log.event}<p className="text-muted-foreground">{log.runId ?? log.traceId ?? ""}{log.sessionId ? <Link className="ml-2 underline" to="/conversation/$sessionId" params={{ sessionId: log.sessionId }}>打开关联会话</Link> : null}</p></div><Button size="sm" variant="ghost" onClick={() => void act(() => navigator.clipboard.writeText(JSON.stringify(log)), "日志已复制")}>复制</Button></div>)}</div>}
  <Button size="sm" variant="outline" disabled={busy} onClick={() => void act(() => maintenanceApi().exportDiagnostics(filter, "logs"), "导出已取消")}>导出当前筛选日志</Button></section>
  <section id="diagnostics-details" className="space-y-3"><h2 className="text-sm font-semibold">临时详细运行信息</h2><p className="text-xs text-muted-foreground">默认关闭。开启后额外显示已有结构化日志中的请求标识、工具名称和 HTTP 方法；仍不读取消息、输入输出或机密。到期和后台重启恢复默认。{detailsExpiry ? ` 到期 ${new Date(detailsExpiry).toLocaleString()}` : " 当前关闭。"}</p><div className="flex flex-wrap gap-2">{[15, 30, 60].map(minutes => <Button key={minutes} size="sm" variant="outline" disabled={busy} onClick={() => void act(async () => { setDetailsExpiry((await maintenanceApi().updateDiagnosticDetails(minutes)).expiresAt); setReport(await maintenanceApi().diagnose()) }, "临时详细运行信息已开启")}>开启 {minutes} 分钟</Button>)}<Button size="sm" variant="ghost" disabled={busy || detailsExpiry === null} onClick={() => void act(async () => { setDetailsExpiry((await maintenanceApi().updateDiagnosticDetails(0)).expiresAt); setReport(await maintenanceApi().diagnose()) }, "详细运行信息已关闭")}>立即关闭</Button></div></section>
  <section id="diagnostics-export" className="space-y-3"><h2 className="text-sm font-semibold">诊断包</h2><p className="text-xs text-muted-foreground">包含版本、平台、检查结果与有限脱敏日志；列出缺失项。排除消息、源码、指令、凭据、机密变量和绝对路径。只保存到所选位置。</p><Button size="sm" variant="outline" disabled={busy} onClick={() => void act(() => maintenanceApi().exportDiagnostics(filter, "diagnostics"), "导出已取消")}>导出诊断包</Button></section>
  <AlertDialog open={restartOpen} onOpenChange={setRestartOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>安全重启后台服务？</AlertDialogTitle><AlertDialogDescription>重启前检查活动任务和终端；尚未收尾时拒绝重启。已有进程、模型连接和终端不会复活。系统常驻服务须先停用。重启失败会显示实际原因。</AlertDialogDescription>{report?.activeWork ? <div className="space-y-2 text-xs text-muted-foreground"><p>当前活动运行 {report.activeWork.runs.length}，后台任务 {report.activeWork.tasks.length}，终端 {report.activeWork.terminals.length}。存在未收尾对象时，本次重启会被拒绝。</p>{[...report.activeWork.runs, ...report.activeWork.tasks].map(work => <p key={work.id}>{work.id} · {work.status} · <Link className="underline" to="/conversation/$sessionId" params={{ sessionId: work.sessionId }}>前往会话收尾</Link></p>)}{report.activeWork.terminals.map(terminal => <p key={terminal.id}>终端 {terminal.id} · {terminal.status}</p>)}</div> : <p className="text-xs text-destructive">未取得活动对象清单；服务仍将在执行时核对并拒绝不安全的重启。</p>}</AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction onClick={() => { setRestartOpen(false); void act(() => maintenanceApi().restart(), "后台服务已重启") }}>确认重启</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>
}
