import { useEffect, useState } from "react"
import { Link } from "@tanstack/react-router"
import { Button } from "@renderer/components/ui/button"
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogAction, AlertDialogCancel } from "@renderer/components/ui/alert-dialog"
import type { CleanupPreview, CleanupResult, MaintenanceBackupResult, StorageReport, StorageRetentionPolicy } from "@shared/maintenance-settings-types"
import { AttachmentStorageSettings } from "./attachment-storage-settings"
import { maintenanceApi } from "./usage-settings"
import { errorMessage } from "./settings-error-message"
import { formatBytes } from "./attachment-storage-format"

export function StorageSettings() {
  const [report, setReport] = useState<StorageReport | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [feedback, setFeedback] = useState("")
  const [source, setSource] = useState(""); const [target, setTarget] = useState(""); const [backup, setBackup] = useState<MaintenanceBackupResult | null>(null); const [restored, setRestored] = useState("")
  const [restoredSettings, setRestoredSettings] = useState("")
  const [includeMemory, setIncludeMemory] = useState(true); const [includeOutput, setIncludeOutput] = useState(false)
  const [cleanupKind, setCleanupKind] = useState<"session" | "log">("session"); const [days, setDays] = useState("90")
  const [preview, setPreview] = useState<CleanupPreview | null>(null); const [selected, setSelected] = useState<string[]>([]); const [cleanupResult, setCleanupResult] = useState<CleanupResult | null>(null)
  const [audits, setAudits] = useState<Record<string, unknown>[]>([])
  const [policy, setPolicy] = useState<StorageRetentionPolicy | null>(null)
  const [confirmation, setConfirmation] = useState<{ title: string; detail: string; apply: () => Promise<unknown> } | null>(null)
  async function act(work: () => Promise<unknown>, message: string) { setBusy(true); try { await work(); setFeedback(message); setError("") } catch (error) { setError(errorMessage(error)) } finally { setBusy(false) } }
  async function scan() { await act(async () => setReport(await maintenanceApi().storage()), "空间统计已刷新") }
  useEffect(() => { void scan(); void Promise.resolve().then(() => maintenanceApi().cleanupAudits()).then(result => setAudits(result.audits)).catch(() => {}); void Promise.resolve().then(() => maintenanceApi().storagePolicy()).then(value => { setPolicy(value); setDays(String(value.days)) }).catch(() => {}) }, [])
  return <div className="flex flex-col gap-8">
    <section id="storage-space" className="space-y-3"><div className="flex justify-between gap-3"><h2 className="text-sm font-semibold">应用数据空间</h2><div className="flex gap-2"><Button size="sm" variant="ghost" disabled={busy} onClick={() => void scan()}>重新扫描</Button><Button size="sm" variant="outline" disabled={busy} onClick={() => void act(() => maintenanceApi().openDirectory(), "数据目录已打开")}>打开数据目录</Button></div></div>
    {error ? <p role="alert" className="text-sm text-destructive">{error}{report ? " 当前仍显示上次扫描结果。" : ""}</p> : null}{feedback ? <p role="status" className="text-xs text-muted-foreground">{feedback}</p> : null}
    {!report ? <p role="status" className="text-sm">{busy ? "正在扫描应用数据…" : "未取得空间统计"}</p> : <><p className="break-all text-xs text-muted-foreground">{report.dataDirectory} · {new Date(report.scannedAt).toLocaleString()} · 合计 {formatBytes(report.totalBytes)} · 剩余 {report.availableBytes === null ? "不支持查询" : formatBytes(report.availableBytes)}</p><div className="divide-y">{report.categories.map(category => <div key={category.id} className="py-3"><div className="flex justify-between gap-3 text-sm"><span>{category.name}</span><span className="tabular-nums">{formatBytes(category.bytes)} · {category.files} 文件</span></div><p className="break-all text-xs text-muted-foreground">{category.paths.join("；")}</p>{category.errors.map(error => <p key={error} className="text-xs text-destructive">{error}</p>)}</div>)}</div></>}
    <p className="text-xs text-muted-foreground">只统计应用管理目录；共享文件只计一次，链接不追踪到外部目录。插件版本缓存和用户数据通过<Link className="underline" to="/plugins">插件维护入口</Link>处理，不能当作普通缓存删除。</p></section>
    <section id="storage-retention" className="space-y-3"><h2 className="text-sm font-semibold">会话保留策略</h2><p className="text-xs text-muted-foreground">默认关闭。开启后，桌面运行期间每小时检查并删除超过保留天数的终态根会话与子会话；活动、排队、待批准及待收束对象保护，结果写入清理审计。恢复数据后自动关闭，原数据不被覆盖。</p>{policy ? <><p className="text-xs">已保存：{policy.enabled ? `自动清理开启，保留 ${policy.days} 天` : "自动清理关闭"}；上次执行 {policy.lastRunAt ? new Date(policy.lastRunAt).toLocaleString() : "尚未执行"}</p><label className="text-xs">保留天数<input aria-label="自动保留天数" type="number" min="1" max="36500" className="ml-2 w-24 rounded border bg-background p-2" value={days} onChange={event => setDays(event.target.value)} /></label><div className="flex gap-2"><Button size="sm" variant="outline" disabled={busy || !Number.isSafeInteger(Number(days)) || Number(days) < 1} onClick={() => setConfirmation({ title: "启用历史会话自动清理？", detail: `桌面运行时，超过 ${days} 天的非活动会话及子会话将被自动删除，无法撤销；活动、待批准和待收束记录保留。请先备份需要保留的内容。`, apply: async () => setPolicy(await maintenanceApi().updateStoragePolicy({ enabled: true, days: Number(days), expected: { enabled: policy.enabled, days: policy.days } })) })}>保存并启用</Button><Button size="sm" variant="ghost" disabled={busy || !policy.enabled} onClick={() => void act(async () => setPolicy(await maintenanceApi().updateStoragePolicy({ enabled: false, days: policy.days, expected: { enabled: policy.enabled, days: policy.days } })), "自动清理已关闭")}>关闭自动清理</Button></div></> : <p className="text-xs text-muted-foreground">尚未取得保留策略；读取失败时不启用自动清理。</p>}</section>
    <section id="storage-attachments" className="space-y-3"><h2 className="text-sm font-semibold">附件健康检查</h2><AttachmentStorageSettings /></section>
    <section id="storage-cleanup" className="space-y-3"><h2 className="text-sm font-semibold">历史会话与轮转日志清理</h2><p className="text-xs text-muted-foreground">默认不自动删除。选择保留天数仅生成本次预览，勾选明确对象后确认执行。保护活动、排队、待批准和待收束记录；插件版本缓存与用户数据不在此清理。</p><div className="flex flex-wrap items-end gap-3"><label className="text-xs">类型<select className="ml-2 rounded border bg-background p-2" value={cleanupKind} onChange={event => { setCleanupKind(event.target.value as "session" | "log"); setPreview(null) }}><option value="session">历史根会话（含子会话）</option><option value="log">已轮转日志</option></select></label><label className="text-xs">保留天数<input aria-label="清理保留天数" className="ml-2 w-20 rounded border bg-background p-2" type="number" min="1" value={days} onChange={event => setDays(event.target.value)} /></label><Button size="sm" variant="outline" disabled={busy || !Number.isFinite(Number(days)) || Number(days) < 1} onClick={() => void act(async () => { setPreview(await maintenanceApi().cleanupPreview({ kind: cleanupKind, olderThan: Date.now() - Number(days) * 86400000 })); setSelected([]); setCleanupResult(null) }, "清理预览已更新")}>预览候选</Button></div>
    {preview ? <><p className="text-xs text-muted-foreground">{preview.scope} · {preview.candidates.length} 个候选 · 预计文件空间 {formatBytes(preview.bytes)}。</p><div className="max-h-72 overflow-auto divide-y">{preview.candidates.map(candidate => <label key={candidate.id} className="flex items-start gap-3 py-2 text-xs"><input type="checkbox" checked={selected.includes(candidate.id)} onChange={event => setSelected(previous => event.target.checked ? [...previous, candidate.id] : previous.filter(id => id !== candidate.id))} /><span>{candidate.label} · {new Date(candidate.updatedAt).toLocaleString()} · {candidate.kind === "session" ? `${candidate.children ?? 0} 个子会话，${candidate.attachments ?? 0} 条附件引用` : formatBytes(candidate.bytes)}<br /><span className="text-muted-foreground">{candidate.id}</span></span></label>)}</div>{preview.protected.length ? <details><summary className="text-xs">已保护 {preview.protected.length} 项</summary>{preview.protected.map(item => <p key={item.id} className="text-xs text-muted-foreground">{item.id}：{item.reason}</p>)}</details> : null}<div className="flex gap-2"><Button size="sm" variant="destructive" disabled={busy || !selected.length} onClick={() => setConfirmation({ title: "删除已勾选的应用数据？", detail: `将删除 ${selected.length} 个所选对象。历史会话包含子会话，删除后不能从本机撤销。附件物理文件单独按引用保护规则清理。执行时再次核对状态；已改变对象跳过。`, apply: async () => { setCleanupResult(await maintenanceApi().cleanupExecute({ previewId: preview.id, ids: selected })); setPreview(null); setSelected([]); setAudits((await maintenanceApi().cleanupAudits()).audits); setReport(await maintenanceApi().storage()) } })}>确认所选清理</Button><Button size="sm" variant="ghost" disabled={busy} onClick={() => { setPreview(null); setSelected([]) }}>取消本次批次</Button></div></> : null}
    {cleanupResult ? <div className="text-xs"><p>实际完成 {cleanupResult.completed.length} 项，跳过 {cleanupResult.skipped.length} 项，失败 {cleanupResult.failures.length} 项，回收文件 {formatBytes(cleanupResult.releasedBytes)}。审计 {cleanupResult.auditId}</p>{[...cleanupResult.skipped, ...cleanupResult.failures].map(item => <p key={item.id} className="text-muted-foreground">{item.id}：{item.reason}</p>)}</div> : null}
    <details><summary className="text-xs">最近清理审计（{audits.length}）</summary>{audits.map((audit, index) => <p key={index} className="py-1 text-xs text-muted-foreground">{new Date(Number(audit.createdAt)).toLocaleString()} · {String(audit.state)} · {String((audit.result as { auditId?: string } | undefined)?.auditId ?? "")}</p>)}</details></section>
    <section id="storage-backup" className="space-y-3"><h2 className="text-sm font-semibold">备份与校验</h2><p className="text-xs text-muted-foreground">备份包含数据库、便签、附件、非机密设置快照，以及所选内容。凭据和用户指令默认排除。服务暂停新任务准入；有活动任务时拒绝创建，请先安全停止任务。</p><label className="flex gap-2 text-xs"><input type="checkbox" checked={includeMemory} onChange={event => setIncludeMemory(event.target.checked)} />包含项目和会话记忆</label><label className="flex gap-2 text-xs"><input type="checkbox" checked={includeOutput} onChange={event => setIncludeOutput(event.target.checked)} />包含运行输出</label>
    <div className="flex flex-wrap gap-2"><Button size="sm" disabled={busy} onClick={() => void act(async () => { const destination = await maintenanceApi().chooseDirectory(); if (!destination) return; const result = await maintenanceApi().backup({ destination, includeMemory, includeOutput }); setBackup(result); setSource(result.path); setReport(await maintenanceApi().storage()) }, "操作结束；备份结果以清单为准")}>选择空目录并备份</Button><Button size="sm" variant="outline" disabled={busy} onClick={() => void act(async () => { const directory = await maintenanceApi().chooseDirectory(); if (!directory) return; const result = await maintenanceApi().verifyBackup(directory); setSource(directory); setBackup(result) }, "备份校验结束")}>选择已有备份并校验</Button></div>
    {backup ? <div className="text-xs text-muted-foreground"><p className="break-all">已校验清单：{backup.path}</p><p>{new Date(backup.manifest.createdAt).toLocaleString()} · 格式 {backup.manifest.version} · 总大小 {backup.totalBytes === undefined ? "未记录" : formatBytes(backup.totalBytes)} · 包含 {Object.entries(backup.manifest.directories).filter(([, included]) => included).map(([name]) => name).join("、")}</p></div> : null}<details><summary className="text-xs">备份创建记录（{report?.backups?.length ?? 0}）</summary>{report?.backups?.map(item => <div key={item.manifest.backupId} className="flex items-start justify-between gap-3 py-2 text-xs"><p className="break-all">{new Date(item.createdAt).toLocaleString()} · {formatBytes(item.bytes)} · 已完成校验<br />{item.path}<br />包含 {Object.entries(item.manifest.directories).filter(([, included]) => included).map(([name]) => name).join("、")}</p><Button size="sm" variant="ghost" disabled={busy} onClick={() => void act(async () => { const result = await maintenanceApi().verifyBackup(item.path); setBackup(result); setSource(result.path) }, "备份已重新校验")}>校验并选择</Button></div>)}</details></section>
    <section id="storage-restore" className="space-y-3"><h2 className="text-sm font-semibold">恢复到新目录</h2><p className="text-xs text-muted-foreground">先校验清单，再恢复到与当前数据完全分离的空目录。恢复不会重建旧进程或继续旧工具。切换失败保留原数据并恢复原位置。</p><p className="break-all text-xs">备份：{source || "尚未选择并校验"}<br />目标：{target || "尚未选择"}</p><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={busy} onClick={() => void act(async () => { const directory = await maintenanceApi().chooseDirectory(); if (directory) setTarget(directory) }, "恢复目标已选择")}>选择空恢复目录</Button><Button size="sm" disabled={busy || !source || !target} onClick={() => setConfirmation({ title: "恢复所选备份？", detail: `备份 ${source}；目标 ${target}。只写入空目标，不改变正在使用的数据。`, apply: async () => { const result = await maintenanceApi().restore({ source, target }); setRestored(result.path); setRestoredSettings(result.settingsSnapshotPath ?? "") } })}>恢复到新目录</Button><Button size="sm" variant="outline" disabled={busy || !restored} onClick={() => setConfirmation({ title: "切换到恢复数据？", detail: `后台将安全关闭并改用 ${restored}。原数据保留；活动任务或终端尚未收尾时拒绝切换。系统常驻服务请先停用。`, apply: async () => { await maintenanceApi().switchData(restored); try { setReport(await maintenanceApi().storage()); const nextPolicy = await maintenanceApi().storagePolicy(); setPolicy(nextPolicy); setDays(String(nextPolicy.days)) } catch (error) { throw new Error(`数据已切换，但维护状态刷新失败：${errorMessage(error)}。仍显示上次扫描结果。`) } } })}>切换到恢复数据</Button></div>{restoredSettings ? <p className="break-all text-xs text-muted-foreground">非机密配置快照已恢复：{restoredSettings}。在<Link className="underline" to="/settings/$section" params={{ section: "general" }}>常规页导入配置</Link>选择此文件和要恢复的分类；切换数据不覆盖当前设备偏好，凭据需重新接入。</p> : null}</section>
    <AlertDialog open={confirmation !== null} onOpenChange={open => { if (!open) setConfirmation(null) }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{confirmation?.title}</AlertDialogTitle><AlertDialogDescription>{confirmation?.detail}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction onClick={() => { const action = confirmation; setConfirmation(null); if (action) void act(action.apply, "操作完成") }}>确认</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>
}
