import { useEffect, useRef, useState } from "react"
import { Button } from "@renderer/components/ui/button"
import { Input } from "@renderer/components/ui/input"
import type { MaintenanceSettingsAPI, UsageFilter, UsagePrice, UsageReport } from "@shared/maintenance-settings-types"
import { errorMessage } from "./settings-error-message"

export function maintenanceApi(): MaintenanceSettingsAPI { const api = (window.desktop as unknown as { maintenance?: MaintenanceSettingsAPI }).maintenance; if (!api) throw new Error("当前应用未接入维护服务"); return api }
export function UsageSettings() {
  const [report, setReport] = useState<UsageReport | null>(null)
  const [filter, setFilter] = useState<UsageFilter>({})
  const [range, setRange] = useState("7")
  const [from, setFrom] = useState(""); const [to, setTo] = useState("")
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [feedback, setFeedback] = useState("")
  const sequence = useRef(0)
  const [price, setPrice] = useState<Omit<UsagePrice, "adoptedAt">>({ provider: "", model: "", currency: "USD", source: "", inputPerMillion: 0, outputPerMillion: 0, cacheReadPerMillion: 0, cacheCreationPerMillion: 0, subscription: false, inputIncludesCache: true })
  const [tokenBudget, setTokenBudget] = useState(""); const [amountBudget, setAmountBudget] = useState("")
  const [budgetCurrency, setBudgetCurrency] = useState("USD")
  const budgetInitialized = useRef(false)
  function activeFilter(): UsageFilter {
    const start = new Date(); start.setHours(0, 0, 0, 0)
    if (range !== "custom") start.setDate(start.getDate() - Number(range) + 1)
    const end = range === "custom" && to ? new Date(`${to}T00:00:00`) : new Date(); if (range === "custom" && to) end.setDate(end.getDate() + 1)
    return { ...filter, from: range === "custom" ? (from ? new Date(`${from}T00:00:00`).getTime() : undefined) : start.getTime(), to: range === "custom" && !to ? undefined : end.getTime() }
  }
  async function load() { const current = ++sequence.current; setBusy(true); try { const next = await maintenanceApi().usage(activeFilter()); if (current === sequence.current) { setReport(next); setError(""); if (!budgetInitialized.current) { budgetInitialized.current = true; setTokenBudget(next.settings.budget.tokens?.toString() ?? ""); setAmountBudget(next.settings.budget.amount?.toString() ?? ""); setBudgetCurrency(next.settings.budget.currency) } } } catch (error) { if (current === sequence.current) setError(errorMessage(error)) } finally { if (current === sequence.current) setBusy(false) } }
  useEffect(() => { void load(); const timer = setInterval(() => { void load() }, 30_000); return () => { sequence.current++; clearInterval(timer) } }, [filter.project, filter.provider, filter.model, range, from, to])
  async function act(work: () => Promise<unknown>, message: string) { setBusy(true); try { const result = await work(); setFeedback(typeof result === "string" ? `已保存到 ${result}` : message); setError(""); await load() } catch (error) { setError(errorMessage(error)) } finally { setBusy(false) } }
  const exceeded = report?.settings.budget.enabled && ((report.settings.budget.tokens !== null && report.totals.input + report.totals.output >= report.settings.budget.tokens) || (report.settings.budget.amount !== null && (report.totals.costs[report.settings.budget.currency] ?? 0) >= report.settings.budget.amount))
  return <div className="flex flex-col gap-8">
    <section id="usage-filters" className="flex flex-col gap-3"><h2 className="text-sm font-semibold">真实模型请求用量</h2><p className="text-xs text-muted-foreground">Token 是模型的输入输出计量单位。统计按当前设备时区；未知用量与已知零值分别显示。每 30 秒刷新。</p>
      <div className="flex flex-wrap items-end gap-3"><label className="text-xs">时间<select aria-label="时间范围" className="ml-2 rounded border bg-background p-2" value={range} onChange={event => setRange(event.target.value)}><option value="1">今天</option><option value="7">最近 7 天</option><option value="30">最近 30 天</option><option value="custom">自定义</option></select></label>
      {range === "custom" ? <><label className="text-xs">开始<Input type="date" value={from} onChange={event => setFrom(event.target.value)} /></label><label className="text-xs">结束（含当天）<Input type="date" value={to} onChange={event => setTo(event.target.value)} /></label></> : null}
      {(["project", "provider", "model"] as const).map(key => <label key={key} className="text-xs">{{ project: "项目", provider: "供应商", model: "模型" }[key]}<select className="ml-2 max-w-64 rounded border bg-background p-2" value={filter[key] ?? ""} onChange={event => setFilter(previous => ({ ...previous, [key]: event.target.value }))}><option value="">全部</option>{(report?.options[key === "project" ? "projects" : key === "provider" ? "providers" : "models"] ?? []).map(value => <option key={value} value={value}>{value}</option>)}</select></label>)}
      <Button variant="ghost" size="sm" disabled={busy} onClick={() => void load()}>刷新</Button></div>
      {busy && !report ? <p role="status" className="text-sm">正在读取请求记录…</p> : null}
      {error ? <p role="alert" className="text-sm text-destructive">{error} {report ? "仍显示上次读取结果。" : ""}</p> : null}{feedback ? <p role="status" className="text-xs text-muted-foreground">{feedback}</p> : null}
    </section>
    {report ? <><section id="usage-summary" className="space-y-3"><div className="grid grid-cols-2 gap-4 sm:grid-cols-3">{[["输入 Token", report.totals.input], ["输出 Token", report.totals.output], ["缓存读取", report.totals.cacheRead], ["缓存创建", report.totals.cacheCreation], ["请求记录", report.totals.requests], ["未知 / 部分", `${report.totals.unknown} / ${report.totals.partial}`]].map(([name, value]) => <div key={name}><p className="text-xs text-muted-foreground">{name}</p><p className="text-lg tabular-nums">{value}</p></div>)}</div>
      <p className="text-xs text-muted-foreground">以上为已知小计；逐次记录不足的历史范围会标为未知。读取时间 {new Date(report.scannedAt).toLocaleString()}。</p>{report.warnings.map(warning => <p key={warning} className="text-xs text-muted-foreground">{warning}</p>)}
      <p className="text-sm">{Object.keys(report.totals.costs).length ? Object.entries(report.totals.costs).map(([currency, amount]) => `估算 ${currency} ${amount.toFixed(6)}`).join("；") : "未提供费用"}。当前请求记录没有供应商账单金额字段，估算不代表扣款。</p>
      {exceeded ? <p role="alert" className="text-sm text-destructive">当前筛选的已知小计已达到提醒阈值；统计不完整时无法判断全部消耗。提醒不会停止任务。</p> : null}
      <div className="flex gap-2"><Button size="sm" variant="outline" disabled={busy} onClick={() => void act(() => maintenanceApi().exportUsage(activeFilter(), "csv"), "导出已取消")}>导出 CSV</Button><Button size="sm" variant="outline" disabled={busy} onClick={() => void act(() => maintenanceApi().exportUsage(activeFilter(), "json"), "导出已取消")}>导出 JSON</Button></div>
    </section>
    <section id="usage-details" className="space-y-3"><h2 className="text-sm font-semibold">请求明细</h2>{!report.requests.length ? <p className="text-sm text-muted-foreground">当前范围没有请求记录。</p> : <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr>{["时间 / 任务", "供应商 / 模型", "输入 / 输出", "缓存读 / 写", "完整性", "费用依据"].map(label => <th key={label} className="p-2 font-medium">{label}</th>)}</tr></thead><tbody>{report.requests.slice(0, 200).map(row => <tr key={row.id} className="border-t"><td className="p-2">{new Date(row.time).toLocaleString()}<br />{row.runId}</td><td className="p-2">{row.provider}<br />{row.model}</td><td className="p-2">{row.inputTokens ?? "未知"} / {row.outputTokens ?? "未知"}</td><td className="p-2">{row.cacheReadTokens ?? "未知"} / {row.cacheCreationTokens ?? "未知"}</td><td className="p-2">{{ complete: "已知", partial: "部分", unknown: "未知" }[row.completeness]}</td><td className="p-2">{row.cost ? `${row.cost.currency} ${row.cost.amount.toFixed(6)}（估算；${row.cost.source}）` : row.subscription ? "费用由订阅承担" : "未提供费用"}</td></tr>)}</tbody></table>{report.requests.length > 200 ? <p className="text-xs text-muted-foreground">页面显示最近 200 条；导出包含当前筛选全部记录。</p> : null}</div>}</section>
    <section id="usage-prices" className="space-y-3"><h2 className="text-sm font-semibold">模型估算价格</h2><p className="text-xs text-muted-foreground">每百万 Token 单位价。保存追加历史，仅用于保存之后的请求；不改写历史依据。订阅费用不能当作普通 API 扣款。</p><div className="grid gap-3 sm:grid-cols-2">{(["provider", "model", "currency", "source"] as const).map(key => <label key={key} className="text-xs">{{ provider: "供应商", model: "模型", currency: "币种", source: "来源（价格表或说明）" }[key]}<Input value={price[key]} onChange={event => setPrice(previous => ({ ...previous, [key]: event.target.value }))} /></label>)}{(["inputPerMillion", "outputPerMillion", "cacheReadPerMillion", "cacheCreationPerMillion"] as const).map(key => <label key={key} className="text-xs">{{ inputPerMillion: "输入价格", outputPerMillion: "输出价格", cacheReadPerMillion: "缓存读取价格", cacheCreationPerMillion: "缓存创建价格" }[key]}<Input type="number" min="0" step="any" value={price[key]} onChange={event => setPrice(previous => ({ ...previous, [key]: Number(event.target.value) }))} /></label>)}</div><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={price.subscription} onChange={event => setPrice(previous => ({ ...previous, subscription: event.target.checked }))} />费用由订阅承担（不计算 API 费用）</label><Button size="sm" disabled={busy} onClick={() => void act(() => maintenanceApi().price(price), "估算价格已保存；新请求采用")}>保存价格</Button>
      <label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={price.inputIncludesCache !== false} onChange={event => setPrice(previous => ({ ...previous, inputIncludesCache: event.target.checked }))} />输入 Token 包含缓存（估算时先扣除缓存后分别计价；输入不含缓存的供应商应取消此项）</label>
      <details><summary className="text-xs">价格历史（{report.settings.prices.length}）</summary>{report.settings.prices.map((item, index) => <p key={index} className="py-1 text-xs text-muted-foreground">{item.provider} / {item.model} · {item.currency} · 输入 {item.inputPerMillion} / 输出 {item.outputPerMillion} / 缓存读 {item.cacheReadPerMillion} / 写 {item.cacheCreationPerMillion} · {item.source} · {new Date(item.adoptedAt).toLocaleString()}{item.subscription ? " · 订阅承担" : ""}</p>)}</details>
    </section>
    <section id="usage-budget" className="space-y-3"><h2 className="text-sm font-semibold">预算提醒</h2><p className="text-xs text-muted-foreground">默认关闭。后台每分钟按本月已知小计检查并发本机通知；本页按当前筛选显示提示，不停止任务。已保存：{report.settings.budget.enabled ? "开启" : "关闭"}；Token {report.settings.budget.tokens ?? "未设置"}，{report.settings.budget.currency} {report.settings.budget.amount ?? "未设置"}。</p><div className="flex flex-wrap gap-3"><label className="text-xs">提醒币种<Input value={budgetCurrency} onChange={event => setBudgetCurrency(event.target.value.toUpperCase())} maxLength={3} /></label><label className="text-xs">Token 阈值<Input type="number" min="1" value={tokenBudget} onChange={event => setTokenBudget(event.target.value)} /></label><label className="text-xs">估算费用阈值（{budgetCurrency}）<Input type="number" min="0" step="any" value={amountBudget} onChange={event => setAmountBudget(event.target.value)} /></label></div><div className="flex gap-2"><Button size="sm" disabled={busy} onClick={() => void act(() => maintenanceApi().budget({ enabled: true, tokens: tokenBudget ? Number(tokenBudget) : null, amount: amountBudget ? Number(amountBudget) : null, currency: budgetCurrency, expected: report.settings.budget }), "预算提醒已保存")}>启用并保存</Button><Button size="sm" variant="ghost" disabled={busy} onClick={() => void act(() => maintenanceApi().budget({ ...report.settings.budget, enabled: false, expected: report.settings.budget }), "预算提醒已关闭")}>关闭提醒</Button></div></section></> : null}
  </div>
}
